USE MECTRONICS;

INSERT INTO MATERIAS (NOMBRE, CREDITOS) VALUES 
('MATEMÁTICAS', 3),
('FÍSICA', 3),
('QUÍMICA', 3),
('BIOLOGÍA', 3),
('HISTORIA', 3),
('LITERATURA', 3),
('GEOGRAFÍA', 3),
('INFORMÁTICA', 3),
('ARTE', 3),
('EDUCACIÓN FÍSICA', 3);

INSERT INTO PROFESORES (NOMBRE, APELLIDO) VALUES 
('CARLOS', 'PÉREZ'),
('ANA', 'GONZÁLEZ'),
('LUIS', 'MARTÍNEZ'),
('MARTA', 'DÍAZ'),
('PEDRO', 'LÓPEZ');

INSERT INTO MATERIAS_PROFESORES (PROFESOR_ID, MATERIA_ID) VALUES 
(1, 3),
(1, 5),
(2, 1),
(2, 2),
(3, 8),
(3, 9),
(4, 7),
(4, 4),
(5, 6),
(5, 10);



